#!/usr/bin/env bash
# 07-git-squash-commits.sh — okf-schema-kb-subcommands
# Generated by Craftsman Wrap-Up Subagent
# DO NOT EDIT MANUALLY

set -euo pipefail

PRD_DIR=".github/changes/archives/001-okf-schema-kb-subcommands"
INITIAL_SHA1="a674cdee995ba4e032cd95a0532756a6428ad2d3"

cd "$(git rev-parse --show-toplevel)"

# Ensure we are on the correct branch
CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
echo "Current branch: $CURRENT_BRANCH"

# Count commits to squash
COMMIT_COUNT=$(git rev-list --count "${INITIAL_SHA1}..HEAD")
echo "Commits to squash: $COMMIT_COUNT"

if [[ "$COMMIT_COUNT" -eq 0 ]]; then
    echo "No commits to squash. Exiting."
    exit 0
fi

# Stage all generated finalization artifacts
git add "$PRD_DIR/07-commit-msg.md"
git add "$PRD_DIR/07-git-squash-commits.sh"
git add "$PRD_DIR/08-gitlab-mr-description.md"
git add "$PRD_DIR/09-achievement-report.md"
git add "$PRD_DIR/09-achievement-report.html"

# Commit the artifacts before squashing
git commit -m "chore(wrap-up): generate finalization artifacts for okf-schema-kb-subcommands

Craftsman-Commit-Type: Coding"

# Perform the squash
# Use the commit message from 07-commit-msg.md
git reset --soft "$INITIAL_SHA1"

git commit -F "$PRD_DIR/07-commit-msg.md" --edit

echo "Squash complete. Review the commit with:"
echo "  git log --oneline -1"
echo "  git show --stat HEAD"
